version: '3'

services:
  mysql:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
    - ./.data/db:/var/lib/mysql

  web:
    image: wordpress
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: password
    ports: 
    - 80:80
    volumes:
    - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    - ./wp-app:/var/www/html
    depends_on:
    - mysql
    links:
    - mysql
